### ISSUE TITLE
Model Availability for Inference

### ISSUE THREAD

**Issue by tushar-31093** [sahilg06/EmoGen#1]
Hi Team,
That's a really good research avenue you have there. Is it possible for your team to share any of the pretrained models that can be directly used by us to test and see the inference? It would be quite useful.

Or
Would we have to train the models ourselves?

Thanks. Look forward to your response.

**Comment by sahilg06** [comment]
Hi @tushar-31093, thanks for your interest in our project. You can directly do inference using this website https://midas.iiitd.edu.in/emo/. It uses one of our trained models. You can follow this video https://youtu.be/bYPX0zp4MY4 to use the demo website. We will also make some pretrained models directly available asap.

**Comment by sahilg06** [comment]
Hi @tushar-31093, you can find some of the model weights here: https://github.com/sahilg06/EmoGen#model-weights
