### ISSUE TITLE
color_syncnet_train.py training not running

### ISSUE THREAD

**Issue by ShangWin** [sahilg06/EmoGen#11]
can you advise on a workaround for this? I have been waiting for color_syncnet_train.py to run for over a few hours numerous times, and nothing is loading or running yet. you mentioned internal changes about tqdm, but what is the potential issue specifically with it?

I could run emotion_disc_train.py training, but not the color_syncnet_train.py training

code entered in cmd line:
python color_syncnet_train.py --data_root ./preprocessed_dataset/ --checkpoint_dir ./checkpoint/

**Comment by sahilg06** [comment]
Hi @ShangWin, I am not sure about the specific issue. Actually, it works for me after a few secs (at max 1-2 minutes). Maybe you can try removing tqdm from the code?
