### ISSUE TITLE
Interactive Demo Error

### ISSUE THREAD

**Issue by P2Oileen** [sahilg06/EmoGen#12]
The interactive demo is not running now, will you fix this problem?

**Comment by sahilg06** [comment]
Thank you for reaching out, will have a look at it.

**Comment by sahilg06** [comment]
This is the link to the pretrained weights of one of our experiments https://drive.google.com/file/d/1yNytUV2qI9RRbB_NMPy-Hgo4b0a-d76F/view?usp=sharing. Till then, you can use it for inference.

**Comment by lililuya** [comment]
Same issue!

**Comment by sahilg06** [comment]
I don't think we'll be able to run the interactive demo further. Sorry for the inconvenience.
