### ISSUE TITLE
color_syncnet_train.py training not working

### ISSUE THREAD

**Issue by charlie89517** [sahilg06/EmoGen#13]
After executing the command "python color_syncnet_train.py --data_root preprocessed_dataset/ --checkpoint_dir C:\EmoGen\checkpoints\syncnet," my CPU usage stays at 100% for several hours, but it seems that the training has not started yet.
I'm not sure at which stage I'm stuck.

![image](https://github.com/sahilg06/EmoGen/assets/117579807/97646a9c-64e1-4367-b1ac-ad4f7c7322d3)

**Comment by charlie89517** [comment]
To let others know, I found the issue, and it was related to the version of librosa. I updated it to version 0.9.0, and it started working correctly.

**Comment by sarthak268** [comment]
Thank you @charlie89517 for the clarification.

**Comment by charlie89517** [comment]
I also noticed that when the librosa version reaches 0.10.1, there may be issues. I recommend keeping the librosa version at 0.9.1.

**Comment by sarthak268** [comment]
Done.
Thank you!
