### ISSUE TITLE
Pretrained inferrence model. 

### ISSUE THREAD

**Issue by rohaantahir** [sahilg06/EmoGen#14]
Hey hatss off to the wonderful research and work. I wanted to ask can you share the pretrained model as the online link https://midas.iiitd.edu.in/emo/ provided is down and we cant test it. If you guys can release the pretrained model it would be great to be used as a benchmark model for my research. 

Thanks and regards

**Comment by sahilg06** [comment]
Hi @rohaantahir, Actually I lost track of our best model weights. But I have some model weights (which may not be best)
I am attaching the links to the weights.
https://drive.google.com/file/d/1yNytUV2qI9RRbB_NMPy-Hgo4b0a-d76F/view?usp=sharing
https://drive.google.com/file/d/1Z_J4xJmlyjue8Th8bl95cC60kOD4sZlZ/view?usp=sharing
I hope it helps!

**Comment by rohaantahir** [comment]
Thanks will give it a try.
