### ISSUE TITLE
KeyError: 'state_dict' in s = checkpoint["state_dict"] inference.py

### ISSUE THREAD

**Issue by MarehanRefaat** [sahilg06/EmoGen#15]
The uploaded model checkpoint "s3fd.pth" has no key called "state_dict". I understood from previous issues this for face_detection model not the whole model so the weights for whole model are available  or not yet? I have a .mp4 video and .wav audio as I want to try your model.

**Comment by sahilg06** [comment]
Actually, I lost track of our best model weights. But I have some model weights (which may not be best)
I am attaching the links to the weights.
https://drive.google.com/file/d/1yNytUV2qI9RRbB_NMPy-Hgo4b0a-d76F/view?usp=sharing
https://drive.google.com/file/d/1Z_J4xJmlyjue8Th8bl95cC60kOD4sZlZ/view?usp=sharing
I hope it helps!
