### ISSUE TITLE
save_sample_images in train.py

### ISSUE THREAD

**Issue by m00yu** [sahilg06/EmoGen#16]
Hello I am training train.py and I am curious what is the meaning of each part in the saved images.

After training, I got results like below. 
Can you explain about what each part of the image is?

Thank you.
![image](https://github.com/sahilg06/EmoGen/assets/113628931/76601200-2cd2-4b4c-a2c7-1283d9c8464b)

**Comment by sahilg06** [comment]
Hi, they are "reference frame || masked frame || generated frame || ground truth frame" respectively.

**Comment by m00yu** [comment]
Thank you! Can you tell me what is the reference frame?

**Comment by sahilg06** [comment]
They are the randomly sampled frames passed as input along with masked frames. You can get more details in the paper itself.
