### ISSUE TITLE
Pretrained checkpoint

### ISSUE THREAD

**Issue by enrico310786** [sahilg06/EmoGen#17]
HI,

your work is very interesting. I would like to test the model with my videos and audios, but the link to the demo is not working. Could you share the pretrained checkpoint thus i can run the inference command?

Thatnk you in advance!

**Comment by sahilg06** [comment]
Hi, 
Actually, I lost track of our best model weights. But I have some model weights (which may not be best)
I am attaching the links to the weights.
https://drive.google.com/file/d/1yNytUV2qI9RRbB_NMPy-Hgo4b0a-d76F/view?usp=sharing
https://drive.google.com/file/d/1Z_J4xJmlyjue8Th8bl95cC60kOD4sZlZ/view?usp=sharing
I hope it helps!
