### ISSUE TITLE
Error while running inference file

### ISSUE THREAD

**Issue by Tafreenzhussain** [sahilg06/EmoGen#2]
Traceback (most recent call last):
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 298, in <module>
    main()
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 265, in main
    model = load_model(args.checkpoint_path)
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 180, in load_model
    s = checkpoint["state_dict"]
KeyError: 'state_dict'

I have trained till 1500 epochs while testing it is throwing this even though I have given the checkpoints path of main model itself. 
Could you please tell me how to resolve this.

Thanks and regards

**Comment by sahilg06** [comment]
I guess your checkpoint is already the state_dict, so you might just try to use:
`s = checkpoint` instead of `s = checkpoint["state_dict"]`

Btw did you change the "saving checkpoint" code in the train.py?

**Comment by Tafreenzhussain** [comment]
If I run it only with checkpoint after removing state_dict then:


Traceback (most recent call last):
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 299, in <module>
    main()
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 266, in main
    model = load_model(args.checkpoint_path)
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 185, in load_model
    model.load_state_dict(new_s)
  File "/home/anaconda3/envs/mead/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Wav2Lip:
	Missing key(s) in state_dict: "face_encoder_blocks.0.0.conv_block.0.weight", "face_encoder_blocks.0.0.conv_block.0.bias", "face_encoder_blocks.0.0.conv_block.1.weight", "face_encoder_blocks.0.0.conv_block.1.bias", "face_encoder_blocks.0.0.conv_block.1.running_mean", "face_encoder_blocks.0.0.conv_block.1.running_var", "face_encoder_blocks.1.0.conv_block.0.weight", "face_encoder_blocks.1.0.conv_block.0.bias", "face_encoder_blocks.1.0.conv_block.1.weight", "face_encoder_blocks.1.0.conv_block.1.bias", "face_encoder_blocks.1.0.conv_block.1.running_mean", "face_encoder_blocks.1.0.conv_block.1.running_var", "face_encoder_blocks.1.1.conv_block.0.weight", "face_encoder_blocks.1.1.conv_block.0.bias", "face_e.............................................. and so on


I didn't change anything in code while training i just gave different paths for training of all three through arguments.

Thanks and regards.

**Comment by Tafreenzhussain** [comment]
This is the complete error which i got:



(mead) root@e2dabc4830c9:/workspace/Wav2Expression/tafreen/EmoGen-master# python inference.py --checkpoint_path final_checkpoints/disc_emo_9000.pth --face temp/test.mp4 --audio temp/audio.wav --emotion HAP
Using cuda for inference.
Reading video frames...
Number of frames available for inference: 67
/workspace/Wav2Expression/tafreen/EmoGen-master/audio.py:100: FutureWarning: Pass sr=16000, n_fft=800 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
(80, 192)
Length of mel chunks: 68
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:06<00:00,  1.38s/it]
Load checkpoint from: final_checkpoints/disc_emo_9000.pth██████████████████████████████████████████████████████████████████| 5/5 [00:06<00:00,  1.06s/it]
  0%|                                                                                                                              | 0/1 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 299, in <module>
    main()
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 266, in main
    model = load_model(args.checkpoint_path)
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 180, in load_model
    s = checkpoint["state_dict"]
KeyError: 'state_dict'

**Comment by sahilg06** [comment]
Actually, you have to give the path to the checkpoint of the main model, but you are providing it for the emotion discriminator (final_checkpoints/disc_emo_9000.pth).

**Comment by Tafreenzhussain** [comment]
yeah my bad.
Thank you

**Comment by Tafreenzhussain** [comment]
Getting this Error while training main model:


Traceback (most recent call last):
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/train.py", line 560, in <module>
    train(device, model, train_data_loader, test_data_loader, optimizer,
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/train.py", line 338, in train
    de_c = disc_emo.forward(g)
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/models/emo_disc.py", line 44, in forward
    n, c, t, w, h = x.size(0), x.size(1), x.size(2), x.size(3), x.size(4)
AttributeError: 'tuple' object has no attribute 'size'


could you please help to solve this.

Thanks and regards

**Comment by sahilg06** [comment]
I have updated the code here: https://github.com/sahilg06/EmoGen/blob/eb5eba1eac862f0064e6ec08b953c859a9f02b08/models/wav2lip.py#L150
It should work now.
Thanks!

**Comment by Tafreenzhussain** [comment]
While testing:



(mead) root@e2dabc4830c9:/workspace/Wav2Expression/tafreen/EmoGen-master# python inference.py --checkpoint_path new_main_model_checkpoints/checkpoint_step000000001.pth --face temp/test.mp4 --audio temp/audio.wav --emotion HAP
Using cuda for inference.
Reading video frames...
Number of frames available for inference: 67
/workspace/Wav2Expression/tafreen/EmoGen-master/audio.py:100: FutureWarning: Pass sr=16000, n_fft=800 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
(80, 192)
Length of mel chunks: 68
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:06<00:00,  1.34s/it]
Load checkpoint from: new_main_model_checkpoints/checkpoint_step000000001.pth██████████████████████████████████████████████| 5/5 [00:06<00:00,  1.02s/it]
Model loaded
  0%|                                                                                                                              | 0/1 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 299, in <module>
    main()
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 278, in main
    pred,_ = model(mel_batch, img_batch, emotion)
  File "/home/anaconda3/envs/mead/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/models/wav2lip.py", line 129, in forward
    x = torch.cat((x, emotion_embedding), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 68 but got size 340 for tensor number 1 in the list.

**Comment by Tafreenzhussain** [comment]
I have encountered another error while testing:

(mead) root@e2dabc4830c9:/workspace/Wav2Expression/tafreen/EmoGen-master# python inference.py --checkpoint_path new_main_model_checkpoints/checkpoint_step000000001.pth --face temp/test.mp4 --audio temp/audio.wav --emotion HAP
Using cuda for inference.
Reading video frames...
Number of frames available for inference: 67
/workspace/Wav2Expression/tafreen/EmoGen-master/audio.py:100: FutureWarning: Pass sr=16000, n_fft=800 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
(80, 192)
Length of mel chunks: 68
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.05s/it]
Load checkpoint from: new_main_model_checkpoints/checkpoint_step000000001.pth██████████████████████████████████████████████| 5/5 [00:05<00:00,  1.21it/s]
Model loaded
  0%|                                                                                                                              | 0/1 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 299, in <module>
    main()
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 278, in main
    pred,_ = model(mel_batch, img_batch, emotion)
  File "/home/anaconda3/envs/mead/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/models/wav2lip.py", line 129, in forward
    x = torch.cat((x, emotion_embedding), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 68 but got size 340 for tensor number 1 in the list.

can you please help me in solving this.

Thanks and regards

**Comment by sahilg06** [comment]
As mentioned [here](https://github.com/sahilg06/EmoGen#inference), you need to comment 2 lines before running the inference.

**Comment by Tafreenzhussain** [comment]
After commenting those lines:


Traceback (most recent call last):
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 305, in <module>
    main()
  File "/workspace/Wav2Expression/tafreen/EmoGen-master/inference.py", line 283, in main
    pred,_ = model(mel_batch, img_batch, emotion)
ValueError: too many values to unpack (expected 2)

**Comment by sahilg06** [comment]
Sorry, there was a small error in the code.
It should be `pred=` instead of `pred,_=`
I have updated the code.

**Comment by Tafreenzhussain** [comment]
https://user-images.githubusercontent.com/84034204/232284650-fc23a9e5-3039-48c1-b492-7ceb62cbc526.mp4

The generated video as a box around face.

**Comment by sahilg06** [comment]
You might not have trained the models properly. I will provide one of the saved checkpoints of the full model asap. You can try the inference with that.

**Comment by sahilg06** [comment]
I have added some of the model weights [here](https://github.com/sahilg06/EmoGen#model-weights). You can try to use them directly.
