### ISSUE TITLE
How do I get the pretraining model parameters ?

### ISSUE THREAD

**Issue by Binn37** [sahilg06/EmoGen#6]
It's an interesting work, especially generating talking face with emotion. I do want to test it using your model weights. Thanks.

**Comment by sarthak268** [comment]
Hi, thanks for your interest in our project. You can directly do inference using this website https://midas.iiitd.edu.in/emo/. It uses one of our trained models. You can follow this video https://youtu.be/bYPX0zp4MY4 to use the demo website.
