### ISSUE TITLE
KeyError: 'state_dicts' when running inference.py

### ISSUE THREAD

**Issue by MMMDY** [sahilg06/EmoGen#7]
F:\DaChuang\EmoGen>python inference.py --checkpoint_path face_detection/detection/sfd/s3fd.pth --face data/0.mp4 --audio data/1.mp3 --emotion HAP --resize_factor 2

Using cuda for inference.
Reading video frames...
Number of frames available for inference: 1997
Extracting raw audio...
                                                                            
Traceback (most recent call last):
  File "inference.py", line 315, in <module>
    main()
  File "inference.py", line 282, in main
    model = load_model(args.checkpoint_path)
  File "inference.py", line 184, in load_model
    s = checkpoint["state_dict"]
KeyError: 'state_dict'

I prepare data 0.mp4 and 1.mp3, I try to inference on laptop with one 1650Ti. But something went wrong.
Could you please tell me how to resolve this.Thank you very much.

**Comment by sahilg06** [comment]
Hi @MMMDY, the path "face_detection/detection/sfd/s3fd.pth" is the checkpoint path for the face detection model that is just required for data preprocessing. It's not the checkpoint for the full model.

**Comment by MMMDY** [comment]
> Hi @MMMDY, the path "face_detection/detection/sfd/s3fd.pth" is the checkpoint path for the face detection model that is just required for data preprocessing. It's not the checkpoint for the full model.

I got it.There is no pretrained inference model.Thank you very much.
