### ISSUE TITLE
Cannot training color_syncnet_train.py

### ISSUE THREAD

**Issue by tommydde** [sahilg06/EmoGen#8]
When I run:
python color_syncnet_train.py --data_root preprocessed_dataset/ --checkpoint_dir folder_to_save_checkpoints/
It only displays and nothing happen 
Epoch: 0
0it [00:00, ?it/s]
Could anyone help me?

**Comment by sahilg06** [comment]
Please wait for 1-2 minutes after running the command. It should work after that. Don't know the exact reason behind this delay. It might be caused by some internal changes in some packages, such as tqdm.

**Comment by ShangWin** [comment]
can you advise on a workaround for this? I have been waiting for color_syncnet_train.py to run for over a few hours numerous times, and nothing is loading or running yet. you mentioned internal changes about tqdm, but what is the potential issue specifically with it?

I could run emotion_disc_train.py training, but not the color_syncnet_train.py training

**code entered in cmd line:**
python color_syncnet_train.py --data_root ./preprocessed_dataset/ --checkpoint_dir ./checkpoint/

**Comment by mumukawayi** [comment]
> can you advise on a workaround for this? I have been waiting for color_syncnet_train.py to run for over a few hours numerous times, and nothing is loading or running yet. you mentioned internal changes about tqdm, but what is the potential issue specifically with it?
> 
> I could run emotion_disc_train.py training, but not the color_syncnet_train.py training
> 
> **code entered in cmd line:** python color_syncnet_train.py --data_root ./preprocessed_dataset/ --checkpoint_dir ./checkpoint/

Have you solved this? I also face the same problem that emotion_disc_train.py can run for thousands epoch but color_syncnet_train.py keep showing following even for days:
`
Epoch: 0
0it [00:00, ?it/s]
`

**Comment by ShangWin** [comment]
> > can you advise on a workaround for this? I have been waiting for color_syncnet_train.py to run for over a few hours numerous times, and nothing is loading or running yet. you mentioned internal changes about tqdm, but what is the potential issue specifically with it?
> > I could run emotion_disc_train.py training, but not the color_syncnet_train.py training
> > **code entered in cmd line:** python color_syncnet_train.py --data_root ./preprocessed_dataset/ --checkpoint_dir ./checkpoint/
> 
> Have you solved this? I also face the same problem that emotion_disc_train.py can run for thousands epoch but color_syncnet_train.py keep showing following even for days: `Epoch: 0 0it [00:00, ?it/s]`

![image](https://github.com/sahilg06/EmoGen/assets/69148496/ba17b45e-dfe6-4653-af45-40ad702c5d27)

![image](https://github.com/sahilg06/EmoGen/assets/69148496/7a85e54b-30a2-46a3-bd10-785864ccc77c)

These are some modifications that I tried making for the issues that I faced, you may try and see if it helps on your end

**Comment by charlie89517** [comment]
> When I run: python color_syncnet_train.py --data_root preprocessed_dataset/ --checkpoint_dir folder_to_save_checkpoints/ It only displays and nothing happen Epoch: 0 0it [00:00, ?it/s] Could anyone help me?

I have the same issue, i changed the "librosa" version to 0.9.0 and it worked
